/* 風格資料庫 — 資料檔
   欄位：id, cat(分類), nameEn(英文名), nameZh(中文名),
         thumb(縮圖，留空，由管理模式上傳),
         promptEn(英文提示詞), promptZh(中文提示詞), desc(圖片說明) */

window.CATEGORIES = ["手繪插畫","復古懷舊","科技未來","漫畫分鏡","地圖路線","商務簡報","電影影視","遊戲動畫","藝術設計","自然科學"];

window.STYLES = [
  { id:1, cat:"手繪插畫", nameEn:"Handwritten / Chalk", nameZh:"手寫粉筆板", thumb:"",
    promptEn:"handwritten chalkboard infographic, dark slate background, white chalk scribbles, doodle icons, arrows, casual classroom notes",
    promptZh:"手寫粉筆黑板資訊圖，深石板色背景，白色粉筆塗寫，塗鴉圖示，箭頭，隨性的課堂筆記感",
    desc:"黑板粉筆手寫風，適合教學、課堂筆記、知識整理類主題。" },
  { id:2, cat:"科技未來", nameEn:"NASA Mission Control", nameZh:"太空任務控制", thumb:"",
    promptEn:"deep navy mission control dashboard, orbital paths, telemetry panels, radar arcs, tiny technical labels, cinematic glow",
    promptZh:"深海軍藍任務控制儀表板，軌道路徑，遙測面板，雷達弧線，細小技術標籤，電影感光暈",
    desc:"NASA 任務控制中心風，適合科技、數據監控、航太主題。" },
  { id:3, cat:"藝術設計", nameEn:"Pop Art Comic", nameZh:"美式普普漫畫", thumb:"",
    promptEn:"pop art comic infographic, halftone dots, bold panels, speech bubbles, punchy primary colors, retro print texture",
    promptZh:"普普藝術漫畫資訊圖，半色調網點，粗框分格，對話框，鮮明三原色，復古印刷質感",
    desc:"美式普普漫畫風，活潑搶眼，適合流行、娛樂、年輕族群主題。" },
  { id:4, cat:"商務簡報", nameEn:"Silicon Valley Startup", nameZh:"矽谷新創簡報", thumb:"",
    promptEn:"clean startup infographic, rounded cards, process flow, minimal line icons, white and pastel UI, soft shadows",
    promptZh:"簡潔新創資訊圖，圓角卡片，流程圖，極簡線條圖示，白底配粉彩 UI，柔和陰影",
    desc:"矽谷新創簡報風，乾淨現代，適合產品介紹、流程說明。" },
  { id:5, cat:"地圖路線", nameEn:"Route 66 Roadtrip", nameZh:"66號公路旅行", thumb:"",
    promptEn:"vintage desert roadtrip map, sun-baked paper, dashed route lines, motel signs, classic cars, travel stickers",
    promptZh:"復古沙漠公路旅行地圖，日曬泛黃紙張，虛線路線，汽車旅館招牌，經典老車，旅行貼紙",
    desc:"美式公路旅行地圖風，懷舊自由，適合旅遊、行程規劃主題。" },
  { id:6, cat:"地圖路線", nameEn:"Mountain Expedition", nameZh:"登山探險日誌", thumb:"",
    promptEn:"old expedition field journal, contour map lines, compass rose, trail sketches, sepia paper texture, handwritten notes",
    promptZh:"老式探險田野日誌，等高線地圖，羅盤玫瑰，路徑速寫，深褐紙質，手寫筆記",
    desc:"探險家手札風，適合登山、戶外、探索紀錄主題。" },
  { id:7, cat:"復古懷舊", nameEn:"Retro Diner", nameZh:"復古美式餐廳", thumb:"",
    promptEn:"1950s diner menu board, red and cream accents, chrome badges, soda icons, retro script typography, menu panels",
    promptZh:"1950 年代美式餐廳菜單板，紅與奶油色點綴，鍍鉻徽章，汽水圖示，復古花體字，菜單分區",
    desc:"50 年代美式餐廳風，復古溫暖，適合餐飲、菜單、懷舊主題。" },
  { id:8, cat:"商務簡報", nameEn:"Corporate Report", nameZh:"企業財經報告", thumb:"",
    promptEn:"fortune 500 annual report page, bar charts, data tables, clean grid, conservative corporate blue layout",
    promptZh:"世界 500 大企業年報頁面，長條圖，數據表格，整齊格線，保守的企業藍版面",
    desc:"企業年報風，正式可信，適合財經、數據、商業報告主題。" },
  { id:9, cat:"遊戲動畫", nameEn:"8-bit Arcade UI", nameZh:"8-bit 遊戲介面", thumb:"",
    promptEn:"pixel art arcade UI, neon grid, sprite mascot, stats windows, retro gaming HUD, saturated 8-bit colors",
    promptZh:"像素風街機介面，霓虹格線，精靈吉祥物，數值視窗，復古遊戲 HUD，飽和 8-bit 色彩",
    desc:"復古電玩像素風，適合遊戲、科技懷舊、趣味主題。" },
  { id:10, cat:"復古懷舊", nameEn:"Wall Street Journal", nameZh:"華爾街報紙", thumb:"",
    promptEn:"vintage newspaper financial page, serif headlines, grayscale columns, small line charts, stipple portrait, editorial layout",
    promptZh:"復古報紙財經版，襯線標題，灰階分欄，小型折線圖，點刻人像，社論式排版",
    desc:"老報紙財經版風，沉穩權威，適合財經、新聞、歷史主題。" },
  { id:11, cat:"漫畫分鏡", nameEn:"Hollywood Storyboard", nameZh:"好萊塢分鏡", thumb:"",
    promptEn:"cinema storyboard sheet, pencil thumbnail frames, camera move arrows, scene notes, production annotations",
    promptZh:"電影分鏡表，鉛筆縮圖格，運鏡箭頭，場景註記，製作標註",
    desc:"電影分鏡腳本風，適合影視、流程、敘事規劃主題。" },
  { id:12, cat:"地圖路線", nameEn:"Temple Path Map", nameZh:"神社古道地圖", thumb:"",
    promptEn:"watercolor cultural road map, temple and torii icons, hand-painted landmarks, warm travel-guide layout",
    promptZh:"水彩人文道路地圖，寺廟與鳥居圖示，手繪地標，溫暖的旅遊指南版面",
    desc:"日式古道水彩地圖風，適合文化旅遊、行程、人文主題。" },
  { id:13, cat:"電影影視", nameEn:"Cinematic Epic", nameZh:"導演史詩電影", thumb:"",
    promptEn:"dramatic sci-fi epic concept board, dark cinematic panels, golden rim light, sense of scale, timeline of shots",
    promptZh:"戲劇性科幻史詩概念板，暗色電影分格，金色輪廓光，宏大尺度感，鏡頭時間軸",
    desc:"史詩科幻電影概念風，氣勢磅礴，適合電影、預告、壯闊主題。" },
  { id:14, cat:"科技未來", nameEn:"Neural Network", nameZh:"神經網路藍圖", thumb:"",
    promptEn:"AI neural network flow diagram, glowing nodes and connections, dark blue data visualization, luminous data paths",
    promptZh:"AI 神經網路流程圖，發光節點與連線，深藍資料視覺化，明亮的資料路徑",
    desc:"AI 神經網路風，科技感強，適合人工智慧、數據、流程主題。" },
  { id:15, cat:"商務簡報", nameEn:"Sports Broadcast", nameZh:"體育轉播資訊圖", thumb:"",
    promptEn:"ESPN-style sports broadcast graphic, dynamic diagonal panels, score bugs, bold condensed typography, action energy",
    promptZh:"ESPN 風體育轉播圖卡，動感斜切分格，比分角標，粗壓縮字體，充滿動能",
    desc:"運動轉播資訊圖風，動感熱血，適合體育、賽事、活力主題。" },
  { id:16, cat:"漫畫分鏡", nameEn:"Noir Comic", nameZh:"黑色漫畫", thumb:"",
    promptEn:"black and white noir comic page, high-contrast panels, detective case notes, heavy ink shadows, film grain",
    promptZh:"黑白黑色電影漫畫頁，高對比分格，偵探案件筆記，濃重墨影，底片顆粒",
    desc:"黑色偵探漫畫風，神祕緊張，適合懸疑、推理、敘事主題。" },
  { id:17, cat:"復古懷舊", nameEn:"Documentary Timeline", nameZh:"紀錄片時間軸", thumb:"",
    promptEn:"documentary timeline infographic, archival paper, sepia photos, historical milestones, museum-style labels",
    promptZh:"紀錄片時間軸資訊圖，檔案紙張，褐調舊照，歷史里程碑，博物館式標籤",
    desc:"紀錄片時間軸風，沉穩敘事，適合歷史、沿革、時間軸主題。" },
  { id:18, cat:"地圖路線", nameEn:"Adventure Map", nameZh:"冒險旅行地圖", thumb:"",
    promptEn:"playful illustrated adventure map, colorful landmarks, dashed travel paths, cute icons, road-trip energy",
    promptZh:"趣味插畫冒險地圖，繽紛地標，虛線旅行路徑，可愛圖示，公路旅行氛圍",
    desc:"插畫冒險地圖風，活潑可愛，適合旅遊、兒童、探索主題。" },
  { id:19, cat:"遊戲動畫", nameEn:"Pixar Journey", nameZh:"皮克斯旅程板", thumb:"",
    promptEn:"warm 3D story journey board, cute stylized characters, bright bouncy colors, emotional milestone scenes",
    promptZh:"溫暖 3D 故事旅程板，可愛風格化角色，明亮活潑色彩，情感里程碑場景",
    desc:"皮克斯動畫旅程風，溫馨療癒，適合故事、成長、情感主題。" },
  { id:20, cat:"復古懷舊", nameEn:"Wild West Poster", nameZh:"西部通緝海報", thumb:"",
    promptEn:"wild west wanted poster, weathered kraft paper, saloon icons, distressed slab-serif type, torn burnt edges",
    promptZh:"狂野西部通緝海報，磨損牛皮紙，酒館圖示，斑駁粗襯線字，撕裂燒焦邊緣",
    desc:"西部通緝海報風，粗獷復古，適合趣味、主題活動、懷舊主題。" },
  { id:21, cat:"遊戲動畫", nameEn:"Anime Opening", nameZh:"動畫開場分鏡", thumb:"",
    promptEn:"anime opening sequence board, kinetic frames, neon city scenery, speed lines, vibrant Japanese pop energy",
    promptZh:"動畫開場分鏡板，動態畫格，霓虹都市場景，速度線，鮮活的日系流行能量",
    desc:"日系動畫開場風，熱血動感，適合動漫、青春、活力主題。" },
  { id:22, cat:"遊戲動畫", nameEn:"RPG Skill Tree", nameZh:"RPG 技能樹", thumb:"",
    promptEn:"fantasy RPG skill tree interface, branching glowing nodes, ability icons, parchment plus dark game UI",
    promptZh:"奇幻 RPG 技能樹介面，分支發光節點，技能圖示，羊皮紙搭配暗色遊戲 UI",
    desc:"RPG 技能樹介面風，適合遊戲、成長路徑、能力地圖主題。" },
  { id:23, cat:"地圖路線", nameEn:"Clean Trail Map", nameZh:"清新版登山路線", thumb:"",
    promptEn:"clean modern trail map infographic, flat icons, color-coded routes, white background, readable labels, outdoor guide",
    promptZh:"簡潔現代登山路線資訊圖，扁平圖示，色彩分類路線，白底，清晰標籤，戶外指南",
    desc:"現代清新登山地圖風，清楚易讀，適合戶外、路線、導覽主題。" },
  { id:24, cat:"科技未來", nameEn:"Cyberpunk Dashboard", nameZh:"賽博美式介面", thumb:"",
    promptEn:"cyberpunk dashboard, neon pink and cyan UI, futuristic city data readouts, dark glassy interface, glitch accents",
    promptZh:"賽博龐克儀表板，霓虹粉與青色 UI，未來都市數據顯示，暗色玻璃介面，故障點綴",
    desc:"賽博龐克介面風，前衛未來，適合科技、潮流、未來主題。" },
  { id:25, cat:"地圖路線", nameEn:"Metro Transit Map", nameZh:"地鐵路線旅程", thumb:"",
    promptEn:"metro transit journey map, colored subway lines, station dots, wayfinding icons, clean schematic on light background",
    promptZh:"地鐵交通旅程圖，彩色路線，站點圓點，指引圖示，淺底簡潔示意圖",
    desc:"地鐵路線圖風，清晰系統化，適合流程、步驟、路線主題。" },
  { id:26, cat:"電影影視", nameEn:"Symmetrical Whimsy", nameZh:"對稱電影美學", thumb:"",
    promptEn:"Wes-Anderson-style symmetrical diagram, centered composition, pastel vintage palette, neat tiny labels",
    promptZh:"魏斯安德森風對稱圖解，置中構圖，粉彩復古色盤，工整的細小標籤",
    desc:"對稱電影美學風，優雅文青，適合質感、品牌、敘事主題。" },
  { id:27, cat:"地圖路線", nameEn:"Fantasy Quest Map", nameZh:"奇幻任務地圖", thumb:"",
    promptEn:"fantasy quest parchment map, illustrated villages, dragons, dotted treasure route, ornate RPG legend",
    promptZh:"奇幻任務羊皮紙地圖，插畫村莊，龍，點狀寶藏路線，華麗 RPG 圖例",
    desc:"奇幻任務地圖風，史詩冒險，適合遊戲、故事、探險主題。" },
  { id:28, cat:"漫畫分鏡", nameEn:"Manga Storyboard", nameZh:"日漫連環分鏡", thumb:"",
    promptEn:"manga storyboard collage, black ink, screentone, speed lines, varied panels, action sound-effect notes",
    promptZh:"日漫連環分鏡拼貼，黑墨，網點，速度線，多變分格，動作狀聲詞註記",
    desc:"日本漫畫分鏡風，動感敘事，適合動漫、故事、流程主題。" },
  { id:29, cat:"科技未來", nameEn:"Space Mission Timeline", nameZh:"太空任務時間軸", thumb:"",
    promptEn:"space mission timeline infographic, planets, rockets, orbital diagrams, dark starfield, glowing trajectory lines",
    promptZh:"太空任務時間軸資訊圖，行星，火箭，軌道圖，暗色星空，發光軌跡線",
    desc:"太空任務時間軸風，浩瀚科技，適合航太、歷程、科普主題。" },
  { id:30, cat:"科技未來", nameEn:"Blueprint", nameZh:"工程藍圖", thumb:"",
    promptEn:"construction blueprint, white technical linework, dimension measurements, cobalt blue background, drafting notes",
    promptZh:"工程施工藍圖，白色技術線稿，尺寸標註，鈷藍背景，製圖註記",
    desc:"工程藍圖風，精準理性，適合工程、設計、結構說明主題。" },
  { id:31, cat:"手繪插畫", nameEn:"Ghibli Journey", nameZh:"吉卜力旅程卷軸", thumb:"",
    promptEn:"Ghibli-inspired journey scroll, whimsical forest map, soft hand-drawn nature scenes, gentle gouache colors",
    promptZh:"吉卜力風旅程卷軸，奇想森林地圖，柔和手繪自然場景，溫潤不透明水彩色",
    desc:"吉卜力手繪旅程風，溫柔療癒，適合自然、故事、童趣主題。" },
  { id:32, cat:"商務簡報", nameEn:"Streaming Pitch Deck", nameZh:"串流平台提案", thumb:"",
    promptEn:"dark streaming pitch deck, title slide, content poster tiles, glowing charts, premium entertainment look",
    promptZh:"暗色串流平台提案簡報，標題頁，內容海報方塊，發光圖表，高級娛樂質感",
    desc:"串流平台提案風，質感高級，適合娛樂、媒體、提案主題。" },
  { id:33, cat:"藝術設計", nameEn:"Isometric Illustration", nameZh:"等距插畫", thumb:"",
    promptEn:"isometric vector infographic, 3D-style buildings and icons, clean diagonal grid, bright flat colors, soft shadows",
    promptZh:"等距向量資訊圖，3D 風建築與圖示，整齊斜向格線，明亮扁平色，柔和陰影",
    desc:"等距 2.5D 插畫風，立體清晰，適合科技、流程、城市主題。" },
  { id:34, cat:"商務簡報", nameEn:"Flat Vector", nameZh:"扁平向量", thumb:"",
    promptEn:"flat design infographic, simple geometric shapes, bold solid colors, minimal line icons, generous white space",
    promptZh:"扁平設計資訊圖，簡單幾何形狀，飽和純色，極簡線條圖示，充裕留白",
    desc:"扁平向量風，簡約現代，適合商務、簡報、通用主題。" },
  { id:35, cat:"手繪插畫", nameEn:"Doodle Notes", nameZh:"塗鴉筆記", thumb:"",
    promptEn:"doodle sketchnote infographic, hand-drawn marker icons, ribbon banners, arrows, hand lettering, white paper, casual fun",
    promptZh:"塗鴉手記資訊圖，手繪麥克筆圖示，緞帶橫幅，箭頭，手寫字，白紙，輕鬆有趣",
    desc:"手繪塗鴉筆記風，活潑親切，適合教學、整理、創意主題。" },
  { id:36, cat:"手繪插畫", nameEn:"Watercolor", nameZh:"水彩手繪", thumb:"",
    promptEn:"watercolor infographic, soft pigment washes, bleeding edges, hand-painted icons, light paper texture, gentle palette",
    promptZh:"水彩資訊圖，柔和顏料暈染，渲染邊緣，手繪圖示，淺色紙質，溫和色盤",
    desc:"水彩手繪風，柔美清新，適合自然、文藝、溫暖主題。" },
  { id:37, cat:"藝術設計", nameEn:"Bauhaus", nameZh:"包浩斯幾何", thumb:"",
    promptEn:"Bauhaus geometric poster infographic, primary colors, circles squares triangles, bold sans-serif, modernist grid",
    promptZh:"包浩斯幾何海報資訊圖，三原色，圓形方形三角形，粗黑體，現代主義格線",
    desc:"包浩斯幾何風，理性前衛，適合設計、藝術、品牌主題。" },
  { id:38, cat:"復古懷舊", nameEn:"Art Deco", nameZh:"裝飾藝術", thumb:"",
    promptEn:"Art Deco infographic, symmetric geometric ornament, gold on deep teal, elegant fan motifs, stylized 1920s typography",
    promptZh:"裝飾藝術資訊圖，對稱幾何裝飾，深青底配金，優雅扇形紋樣，風格化的 1920 年代字體",
    desc:"Art Deco 裝飾藝術風，奢華典雅，適合高端、復古、品牌主題。" },
  { id:39, cat:"藝術設計", nameEn:"Art Nouveau", nameZh:"新藝術風", thumb:"",
    promptEn:"Art Nouveau poster infographic, ornate flowing floral lines, whiplash curves, muted jewel tones, decorative frames",
    promptZh:"新藝術海報資訊圖，華麗流動花卉線條，鞭索曲線，低調寶石色，裝飾性框邊",
    desc:"新藝術風，優雅華麗，適合藝文、美妝、典雅主題。" },
  { id:40, cat:"科技未來", nameEn:"Vaporwave", nameZh:"蒸氣波", thumb:"",
    promptEn:"vaporwave infographic, neon pink and teal gradients, retro grid horizon, glitchy chrome type, 80s surreal mood",
    promptZh:"蒸氣波資訊圖，霓虹粉與青色漸層，復古格線地平線，故障鍍鉻字，80 年代超現實氛圍",
    desc:"蒸氣波風，迷幻復古，適合潮流、音樂、未來懷舊主題。" },
  { id:41, cat:"科技未來", nameEn:"Synthwave", nameZh:"合成波", thumb:"",
    promptEn:"synthwave infographic, glowing sunset grid, neon outlines, dark purple sky, retro-futuristic 80s energy",
    promptZh:"合成波資訊圖，發光夕陽格線，霓虹輪廓，深紫天空，復古未來的 80 年代能量",
    desc:"合成波風，霓虹熱血，適合音樂、科技、復古未來主題。" },
  { id:42, cat:"復古懷舊", nameEn:"Steampunk", nameZh:"蒸汽龐克", thumb:"",
    promptEn:"steampunk infographic, brass gears, copper pipes, aged parchment, Victorian gauges, sepia mechanical diagrams",
    promptZh:"蒸汽龐克資訊圖，黃銅齒輪，銅管，泛黃羊皮紙，維多利亞儀表，褐調機械圖",
    desc:"蒸汽龐克風，復古機械感，適合科技、奇幻、工藝主題。" },
  { id:43, cat:"復古懷舊", nameEn:"Ukiyo-e Woodblock", nameZh:"浮世繪", thumb:"",
    promptEn:"ukiyo-e woodblock infographic, flat traditional Japanese print, wave motifs, muted earthy ink, bordered panels",
    promptZh:"浮世繪木刻版畫資訊圖，扁平的傳統日本版畫，海浪紋樣，低彩大地墨色，帶框分格",
    desc:"浮世繪版畫風，東方古典，適合日式、文化、傳統主題。" },
  { id:44, cat:"手繪插畫", nameEn:"Paper Cut Collage", nameZh:"剪紙拼貼", thumb:"",
    promptEn:"layered paper-cut infographic, stacked construction-paper shapes, soft drop shadows, textured collage, warm palette",
    promptZh:"層疊剪紙資訊圖，堆疊的色紙形狀，柔和投影，質感拼貼，溫暖色盤",
    desc:"剪紙拼貼風，溫暖手作，適合兒童、故事、手作主題。" },
  { id:45, cat:"藝術設計", nameEn:"Risograph Print", nameZh:"孔版印刷", thumb:"",
    promptEn:"risograph print infographic, two-color overprint, grainy texture, slight misregistration, bold flat shapes",
    promptZh:"孔版印刷資訊圖，雙色疊印，顆粒質感，些微套印錯位，粗獷扁平形狀",
    desc:"Riso 孔版印刷風，質樸文青，適合設計、刊物、藝術主題。" },
  { id:46, cat:"地圖路線", nameEn:"Topographic", nameZh:"等高線地形", thumb:"",
    promptEn:"topographic map infographic, layered elevation contour lines, terrain shading, minimal labels, muted earth tones",
    promptZh:"等高線地形資訊圖，層疊高程等高線，地形陰影，極簡標籤，低彩大地色",
    desc:"等高線地形風，自然理性，適合地理、戶外、數據主題。" },
  { id:47, cat:"自然科學", nameEn:"Botanical Plate", nameZh:"植物科學圖鑑", thumb:"",
    promptEn:"vintage botanical plate infographic, detailed plant illustration, latin labels, aged cream paper, scientific elegance",
    promptZh:"復古植物圖鑑資訊圖，細緻植物插畫，拉丁文標籤，泛黃米色紙，科學的優雅",
    desc:"古典植物圖鑑風，細緻典雅，適合自然、科普、教育主題。" },
  { id:48, cat:"自然科學", nameEn:"Nature Journal", nameZh:"自然觀察筆記", thumb:"",
    promptEn:"nature journal infographic, hand-drawn field sketches, watercolor specimens, handwritten notes, kraft paper",
    promptZh:"自然觀察筆記資訊圖，手繪田野速寫，水彩標本，手寫筆記，牛皮紙",
    desc:"自然觀察手記風，質樸溫暖，適合自然、教學、紀錄主題。" },
  { id:49, cat:"自然科學", nameEn:"Anatomical Diagram", nameZh:"解剖圖解", thumb:"",
    promptEn:"vintage anatomical diagram infographic, cross-section illustration, labelled callouts, fine engraving line shading",
    promptZh:"復古解剖圖解資訊圖，剖面插畫，標示引線，細緻雕版線影",
    desc:"古典解剖圖風，精細專業，適合醫學、科普、結構主題。" },
  { id:50, cat:"科技未來", nameEn:"Glassmorphism", nameZh:"玻璃擬態", thumb:"",
    promptEn:"glassmorphism dashboard infographic, frosted translucent cards, soft blur, vivid gradient background, modern UI",
    promptZh:"玻璃擬態儀表板資訊圖，霧面半透明卡片，柔和模糊，鮮豔漸層背景，現代 UI",
    desc:"玻璃擬態風，現代通透，適合科技、UI、產品主題。" },
  { id:51, cat:"遊戲動畫", nameEn:"Claymation", nameZh:"黏土風", thumb:"",
    promptEn:"clay 3D infographic, soft molded plasticine icons, rounded shapes, playful pastels, tactile stop-motion look",
    promptZh:"黏土 3D 資訊圖，柔軟塑形的黏土圖示，圓潤形狀，活潑粉彩，觸感定格動畫感",
    desc:"黏土定格動畫風，可愛療癒，適合兒童、趣味、手作主題。" },
  { id:52, cat:"遊戲動畫", nameEn:"LEGO Bricks", nameZh:"樂高積木", thumb:"",
    promptEn:"LEGO brick infographic, blocky plastic pieces, minifigure scenes, bright primary studs, toy-world assembly",
    promptZh:"樂高積木資訊圖，方塊塑膠零件，小人偶場景，明亮三原色顆粒，玩具世界組裝",
    desc:"樂高積木風，趣味童心，適合兒童、創意、組裝主題。" },
  { id:53, cat:"科技未來", nameEn:"Low Poly", nameZh:"低多邊形", thumb:"",
    promptEn:"low poly infographic, faceted geometric 3D shapes, gradient triangles, crisp digital render, cool palette",
    promptZh:"低多邊形資訊圖，切面幾何 3D 形狀，漸層三角面，俐落數位渲染，冷色盤",
    desc:"低多邊形風，數位俐落，適合科技、抽象、現代主題。" },
  { id:54, cat:"科技未來", nameEn:"Glitch Art", nameZh:"故障藝術", thumb:"",
    promptEn:"glitch art infographic, datamosh distortion, RGB channel split, scanlines, broken-screen digital aesthetic",
    promptZh:"故障藝術資訊圖，資料破壞扭曲，RGB 色版分離，掃描線，破碎螢幕的數位美學",
    desc:"故障藝術風，前衛實驗，適合潮流、音樂、科技主題。" },
  { id:55, cat:"藝術設計", nameEn:"Neo-Memphis", nameZh:"孟菲斯普普", thumb:"",
    promptEn:"Neo-Memphis infographic, playful geometric confetti shapes, squiggles, bold 80s colors, fun pattern blocks",
    promptZh:"新孟菲斯資訊圖，趣味幾何碎紙形狀，波浪線，大膽 80 年代色彩，趣味圖案塊",
    desc:"孟菲斯普普風，繽紛玩味，適合年輕、活動、趣味主題。" },
  { id:56, cat:"手繪插畫", nameEn:"Minimal Line Art", nameZh:"極簡線稿", thumb:"",
    promptEn:"minimalist single-line infographic, continuous contour icons, lots of white space, one accent color, elegant",
    promptZh:"極簡單線資訊圖，連續輪廓線圖示，大量留白，單一強調色，優雅",
    desc:"極簡單線稿風，優雅留白，適合質感、品牌、文藝主題。" },
  { id:57, cat:"復古懷舊", nameEn:"Retro Sci-Fi", nameZh:"復古太空", thumb:"",
    promptEn:"1950s retro sci-fi infographic, atomic-age rockets, ringed planets, muted teal and orange, vintage poster print",
    promptZh:"1950 年代復古科幻資訊圖，原子時代火箭，環狀行星，低彩青與橘，復古海報印刷",
    desc:"復古太空科幻風，懷舊趣味，適合科普、太空、復古主題。" },
  { id:58, cat:"藝術設計", nameEn:"Mixed Media Collage", nameZh:"蒙太奇拼貼", thumb:"",
    promptEn:"mixed-media collage infographic, torn paper, washi tape, magazine cutouts, handwriting, layered scrapbook texture",
    promptZh:"混合媒材拼貼資訊圖，撕紙，和紙膠帶，雜誌剪貼，手寫字，層疊剪貼簿質感",
    desc:"蒙太奇拼貼風，手作隨性，適合創意、手帳、藝術主題。" },
  { id:59, cat:"藝術設計", nameEn:"Stained Glass", nameZh:"彩繪玻璃", thumb:"",
    promptEn:"stained glass infographic, leaded color segments, glowing jewel panels, bold black outlines, cathedral motif",
    promptZh:"彩繪玻璃資訊圖，鉛條分割色塊，發光寶石面板，粗黑輪廓，教堂母題",
    desc:"彩繪玻璃風，華麗莊嚴，適合藝術、文化、典雅主題。" },
  { id:60, cat:"手繪插畫", nameEn:"Kawaii Journal", nameZh:"卡哇伊手帳", thumb:"",
    promptEn:"kawaii infographic, cute pastel mascots, rounded bubbly icons, sticker decorations, soft cheerful palette",
    promptZh:"卡哇伊資訊圖，可愛粉彩吉祥物，圓潤泡泡圖示，貼紙裝飾，柔和歡樂色盤",
    desc:"卡哇伊手帳風，可愛甜美，適合兒童、手帳、療癒主題。" },
  { id:61, cat:"商務簡報", nameEn:"Luxury Gold", nameZh:"黑金奢華", thumb:"",
    promptEn:"luxury infographic, matte black background, gold foil lines, serif headings, elegant minimal premium layout",
    promptZh:"奢華資訊圖，霧面黑背景，燙金線條，襯線標題，優雅極簡的高級版面",
    desc:"黑金奢華風，高端質感，適合精品、品牌、高端主題。" },
  { id:62, cat:"科技未來", nameEn:"Hologram UI", nameZh:"全像投影", thumb:"",
    promptEn:"holographic HUD infographic, translucent cyan projections, glowing wireframes, floating data panels, sci-fi interface",
    promptZh:"全像 HUD 資訊圖，半透明青色投影，發光線框，懸浮資料面板，科幻介面",
    desc:"全像投影介面風，未來科技，適合科技、未來、數據主題。" },
  { id:63, cat:"手繪插畫", nameEn:"Storybook", nameZh:"童書插畫", thumb:"",
    promptEn:"children's storybook infographic, soft gouache illustration, friendly characters, warm rounded scenes, cozy palette",
    promptZh:"童書資訊圖，柔和不透明水彩插畫，親切角色，溫暖圓潤場景，溫馨色盤",
    desc:"童書插畫風，溫馨童趣，適合兒童、故事、教育主題。" },
  { id:64, cat:"電影影視", nameEn:"Movie Poster", nameZh:"電影海報", thumb:"",
    promptEn:"blockbuster movie poster infographic, dramatic lighting, layered character montage, bold title treatment, epic mood",
    promptZh:"商業大片電影海報資訊圖，戲劇性光影，層疊角色蒙太奇，強烈標題設計，史詩氛圍",
    desc:"商業電影海報風，震撼吸睛，適合宣傳、活動、史詩主題。" }
];
