/* ============================================================
   風格資料庫 — 內建風格清單
   ------------------------------------------------------------
   想新增 / 修改風格，直接編輯這個檔案即可（不用動 index.html）。
   每筆欄位：
     id      : 唯一編號
     cat     : 分類（需是 CATEGORIES 之一）
     nameEn  : 卡片大標（英文風格名）
     nameZh  : 卡片副標（中文說明）
     prompt  : 一鍵複製的提示詞（英文，資訊圖導向關鍵字）
     thumb   : 縮圖路徑；檔案不存在時會自動顯示分類佔位圖
   ============================================================ */

window.CATEGORIES = [
  "手繪插畫", "復古懷舊", "科技未來", "漫畫分鏡", "地圖路線",
  "商務簡報", "電影影視", "遊戲動畫", "藝術設計", "自然科學"
];

window.STYLES = [
  // ── 原始 32 個（提示詞已重寫精簡） ──────────────────────
  { id: 1,  cat: "手繪插畫", nameEn: "Handwritten / Chalk",   nameZh: "手寫粉筆板",   thumb: "thumbs/thumb_01.png",
    prompt: "handwritten chalkboard infographic, dark slate background, white chalk scribbles, doodle icons, arrows, casual classroom notes" },
  { id: 2,  cat: "科技未來", nameEn: "NASA Mission Control",  nameZh: "太空任務控制", thumb: "thumbs/thumb_02.png",
    prompt: "deep navy mission control dashboard, orbital paths, telemetry panels, radar arcs, tiny technical labels, cinematic glow" },
  { id: 3,  cat: "藝術設計", nameEn: "Pop Art Comic",         nameZh: "美式普普漫畫", thumb: "thumbs/thumb_03.png",
    prompt: "pop art comic infographic, halftone dots, bold panels, speech bubbles, punchy primary colors, retro print texture" },
  { id: 4,  cat: "商務簡報", nameEn: "Silicon Valley Startup", nameZh: "矽谷新創簡報", thumb: "thumbs/thumb_04.png",
    prompt: "clean startup infographic, rounded cards, process flow, minimal line icons, white and pastel UI, soft shadows" },
  { id: 5,  cat: "地圖路線", nameEn: "Route 66 Roadtrip",     nameZh: "66號公路旅行", thumb: "thumbs/thumb_05.png",
    prompt: "vintage desert roadtrip map, sun-baked paper, dashed route lines, motel signs, classic cars, travel stickers" },
  { id: 6,  cat: "地圖路線", nameEn: "Mountain Expedition",   nameZh: "登山探險日誌", thumb: "thumbs/thumb_06.png",
    prompt: "old expedition field journal, contour map lines, compass rose, trail sketches, sepia paper texture, handwritten notes" },
  { id: 7,  cat: "復古懷舊", nameEn: "Retro Diner",           nameZh: "復古美式餐廳", thumb: "thumbs/thumb_07.png",
    prompt: "1950s diner menu board, red and cream accents, chrome badges, soda icons, retro script typography, menu panels" },
  { id: 8,  cat: "商務簡報", nameEn: "Corporate Report",      nameZh: "企業財經報告", thumb: "thumbs/thumb_08.png",
    prompt: "fortune 500 annual report page, bar charts, data tables, clean grid, conservative corporate blue layout" },
  { id: 9,  cat: "遊戲動畫", nameEn: "8-bit Arcade UI",       nameZh: "8-bit 遊戲介面", thumb: "thumbs/thumb_09.png",
    prompt: "pixel art arcade UI, neon grid, sprite mascot, stats windows, retro gaming HUD, saturated 8-bit colors" },
  { id: 10, cat: "復古懷舊", nameEn: "Wall Street Journal",   nameZh: "華爾街報紙",   thumb: "thumbs/thumb_10.png",
    prompt: "vintage newspaper financial page, serif headlines, grayscale columns, small line charts, stipple portrait, editorial layout" },
  { id: 11, cat: "漫畫分鏡", nameEn: "Hollywood Storyboard",  nameZh: "好萊塢分鏡",   thumb: "thumbs/thumb_11.png",
    prompt: "cinema storyboard sheet, pencil thumbnail frames, camera move arrows, scene notes, production annotations" },
  { id: 12, cat: "地圖路線", nameEn: "Temple Path Map",       nameZh: "神社古道地圖", thumb: "thumbs/thumb_12.png",
    prompt: "watercolor cultural road map, temple and torii icons, hand-painted landmarks, warm travel-guide layout" },
  { id: 13, cat: "電影影視", nameEn: "Cinematic Epic",        nameZh: "導演史詩電影", thumb: "thumbs/thumb_13.png",
    prompt: "dramatic sci-fi epic concept board, dark cinematic panels, golden rim light, sense of scale, timeline of shots" },
  { id: 14, cat: "科技未來", nameEn: "Neural Network",        nameZh: "神經網路藍圖", thumb: "thumbs/thumb_14.png",
    prompt: "AI neural network flow diagram, glowing nodes and connections, dark blue data visualization, luminous data paths" },
  { id: 15, cat: "商務簡報", nameEn: "Sports Broadcast",      nameZh: "體育轉播資訊圖", thumb: "thumbs/thumb_15.png",
    prompt: "ESPN-style sports broadcast graphic, dynamic diagonal panels, score bugs, bold condensed typography, action energy" },
  { id: 16, cat: "漫畫分鏡", nameEn: "Noir Comic",            nameZh: "黑色漫畫",     thumb: "thumbs/thumb_16.png",
    prompt: "black and white noir comic page, high-contrast panels, detective case notes, heavy ink shadows, film grain" },
  { id: 17, cat: "復古懷舊", nameEn: "Documentary Timeline",  nameZh: "紀錄片時間軸", thumb: "thumbs/thumb_17.png",
    prompt: "documentary timeline infographic, archival paper, sepia photos, historical milestones, museum-style labels" },
  { id: 18, cat: "地圖路線", nameEn: "Adventure Map",         nameZh: "冒險旅行地圖", thumb: "thumbs/thumb_18.png",
    prompt: "playful illustrated adventure map, colorful landmarks, dashed travel paths, cute icons, road-trip energy" },
  { id: 19, cat: "遊戲動畫", nameEn: "Pixar Journey",         nameZh: "皮克斯旅程板", thumb: "thumbs/thumb_19.png",
    prompt: "warm 3D story journey board, cute stylized characters, bright bouncy colors, emotional milestone scenes" },
  { id: 20, cat: "復古懷舊", nameEn: "Wild West Poster",      nameZh: "西部通緝海報", thumb: "thumbs/thumb_20.png",
    prompt: "wild west wanted poster, weathered kraft paper, saloon icons, distressed slab-serif type, torn burnt edges" },
  { id: 21, cat: "遊戲動畫", nameEn: "Anime Opening",         nameZh: "動畫開場分鏡", thumb: "thumbs/thumb_21.png",
    prompt: "anime opening sequence board, kinetic frames, neon city scenery, speed lines, vibrant Japanese pop energy" },
  { id: 22, cat: "遊戲動畫", nameEn: "RPG Skill Tree",        nameZh: "RPG 技能樹",   thumb: "thumbs/thumb_22.png",
    prompt: "fantasy RPG skill tree interface, branching glowing nodes, ability icons, parchment plus dark game UI" },
  { id: 23, cat: "地圖路線", nameEn: "Clean Trail Map",       nameZh: "清新版登山路線", thumb: "thumbs/thumb_23.png",
    prompt: "clean modern trail map infographic, flat icons, color-coded routes, white background, readable labels, outdoor guide" },
  { id: 24, cat: "科技未來", nameEn: "Cyberpunk Dashboard",   nameZh: "賽博美式介面", thumb: "thumbs/thumb_24.png",
    prompt: "cyberpunk dashboard, neon pink and cyan UI, futuristic city data readouts, dark glassy interface, glitch accents" },
  { id: 25, cat: "地圖路線", nameEn: "Metro Transit Map",     nameZh: "地鐵路線旅程", thumb: "thumbs/thumb_25.png",
    prompt: "metro transit journey map, colored subway lines, station dots, wayfinding icons, clean schematic on light background" },
  { id: 26, cat: "電影影視", nameEn: "Symmetrical Whimsy",    nameZh: "對稱電影美學", thumb: "thumbs/thumb_26.png",
    prompt: "Wes-Anderson-style symmetrical diagram, centered composition, pastel vintage palette, neat tiny labels" },
  { id: 27, cat: "地圖路線", nameEn: "Fantasy Quest Map",     nameZh: "奇幻任務地圖", thumb: "thumbs/thumb_27.png",
    prompt: "fantasy quest parchment map, illustrated villages, dragons, dotted treasure route, ornate RPG legend" },
  { id: 28, cat: "漫畫分鏡", nameEn: "Manga Storyboard",      nameZh: "日漫連環分鏡", thumb: "thumbs/thumb_28.png",
    prompt: "manga storyboard collage, black ink, screentone, speed lines, varied panels, action sound-effect notes" },
  { id: 29, cat: "科技未來", nameEn: "Space Mission Timeline", nameZh: "太空任務時間軸", thumb: "thumbs/thumb_29.png",
    prompt: "space mission timeline infographic, planets, rockets, orbital diagrams, dark starfield, glowing trajectory lines" },
  { id: 30, cat: "科技未來", nameEn: "Blueprint",             nameZh: "工程藍圖",     thumb: "thumbs/thumb_30.png",
    prompt: "construction blueprint, white technical linework, dimension measurements, cobalt blue background, drafting notes" },
  { id: 31, cat: "手繪插畫", nameEn: "Ghibli Journey",        nameZh: "吉卜力旅程卷軸", thumb: "thumbs/thumb_31.png",
    prompt: "Ghibli-inspired journey scroll, whimsical forest map, soft hand-drawn nature scenes, gentle gouache colors" },
  { id: 32, cat: "商務簡報", nameEn: "Streaming Pitch Deck",  nameZh: "串流平台提案", thumb: "thumbs/thumb_32.png",
    prompt: "dark streaming pitch deck, title slide, content poster tiles, glowing charts, premium entertainment look" },

  // ── 新增風格（重寫提示詞、自行生圖） ─────────────────────
  { id: 33, cat: "藝術設計", nameEn: "Isometric Illustration", nameZh: "等距插畫",   thumb: "thumbs/thumb_33.png",
    prompt: "isometric vector infographic, 3D-style buildings and icons, clean diagonal grid, bright flat colors, soft shadows" },
  { id: 34, cat: "商務簡報", nameEn: "Flat Vector",           nameZh: "扁平向量",     thumb: "thumbs/thumb_34.png",
    prompt: "flat design infographic, simple geometric shapes, bold solid colors, minimal line icons, generous white space" },
  { id: 35, cat: "手繪插畫", nameEn: "Doodle Notes",          nameZh: "塗鴉筆記",     thumb: "thumbs/thumb_35.png",
    prompt: "doodle sketchnote infographic, hand-drawn marker icons, ribbon banners, arrows, hand lettering, white paper, casual fun" },
  { id: 36, cat: "手繪插畫", nameEn: "Watercolor",            nameZh: "水彩手繪",     thumb: "thumbs/thumb_36.png",
    prompt: "watercolor infographic, soft pigment washes, bleeding edges, hand-painted icons, light paper texture, gentle palette" },
  { id: 37, cat: "藝術設計", nameEn: "Bauhaus",               nameZh: "包浩斯幾何",   thumb: "thumbs/thumb_37.png",
    prompt: "Bauhaus geometric poster infographic, primary colors, circles squares triangles, bold sans-serif, modernist grid" },
  { id: 38, cat: "復古懷舊", nameEn: "Art Deco",              nameZh: "裝飾藝術",     thumb: "thumbs/thumb_38.png",
    prompt: "Art Deco infographic, symmetric geometric ornament, gold on deep teal, elegant fan motifs, stylized 1920s typography" },
  { id: 39, cat: "藝術設計", nameEn: "Art Nouveau",           nameZh: "新藝術風",     thumb: "thumbs/thumb_39.png",
    prompt: "Art Nouveau poster infographic, ornate flowing floral lines, whiplash curves, muted jewel tones, decorative frames" },
  { id: 40, cat: "科技未來", nameEn: "Vaporwave",             nameZh: "蒸氣波",       thumb: "thumbs/thumb_40.png",
    prompt: "vaporwave infographic, neon pink and teal gradients, retro grid horizon, glitchy chrome type, 80s surreal mood" },
  { id: 41, cat: "科技未來", nameEn: "Synthwave",             nameZh: "合成波",       thumb: "thumbs/thumb_41.png",
    prompt: "synthwave infographic, glowing sunset grid, neon outlines, dark purple sky, retro-futuristic 80s energy" },
  { id: 42, cat: "復古懷舊", nameEn: "Steampunk",             nameZh: "蒸汽龐克",     thumb: "thumbs/thumb_42.png",
    prompt: "steampunk infographic, brass gears, copper pipes, aged parchment, Victorian gauges, sepia mechanical diagrams" },
  { id: 43, cat: "復古懷舊", nameEn: "Ukiyo-e Woodblock",     nameZh: "浮世繪",       thumb: "thumbs/thumb_43.png",
    prompt: "ukiyo-e woodblock infographic, flat traditional Japanese print, wave motifs, muted earthy ink, bordered panels" },
  { id: 44, cat: "手繪插畫", nameEn: "Paper Cut Collage",     nameZh: "剪紙拼貼",     thumb: "thumbs/thumb_44.png",
    prompt: "layered paper-cut infographic, stacked construction-paper shapes, soft drop shadows, textured collage, warm palette" },
  { id: 45, cat: "藝術設計", nameEn: "Risograph Print",       nameZh: "孔版印刷",     thumb: "thumbs/thumb_45.png",
    prompt: "risograph print infographic, two-color overprint, grainy texture, slight misregistration, bold flat shapes" },
  { id: 46, cat: "地圖路線", nameEn: "Topographic",           nameZh: "等高線地形",   thumb: "thumbs/thumb_46.png",
    prompt: "topographic map infographic, layered elevation contour lines, terrain shading, minimal labels, muted earth tones" },
  { id: 47, cat: "自然科學", nameEn: "Botanical Plate",       nameZh: "植物科學圖鑑", thumb: "thumbs/thumb_47.png",
    prompt: "vintage botanical plate infographic, detailed plant illustration, latin labels, aged cream paper, scientific elegance" },
  { id: 48, cat: "自然科學", nameEn: "Nature Journal",        nameZh: "自然觀察筆記", thumb: "thumbs/thumb_48.png",
    prompt: "nature journal infographic, hand-drawn field sketches, watercolor specimens, handwritten notes, kraft paper" },
  { id: 49, cat: "自然科學", nameEn: "Anatomical Diagram",    nameZh: "解剖圖解",     thumb: "thumbs/thumb_49.png",
    prompt: "vintage anatomical diagram infographic, cross-section illustration, labelled callouts, fine engraving line shading" },
  { id: 50, cat: "科技未來", nameEn: "Glassmorphism",         nameZh: "玻璃擬態",     thumb: "thumbs/thumb_50.png",
    prompt: "glassmorphism dashboard infographic, frosted translucent cards, soft blur, vivid gradient background, modern UI" },
  { id: 51, cat: "遊戲動畫", nameEn: "Claymation",            nameZh: "黏土風",       thumb: "thumbs/thumb_51.png",
    prompt: "clay 3D infographic, soft molded plasticine icons, rounded shapes, playful pastels, tactile stop-motion look" },
  { id: 52, cat: "遊戲動畫", nameEn: "LEGO Bricks",           nameZh: "樂高積木",     thumb: "thumbs/thumb_52.png",
    prompt: "LEGO brick infographic, blocky plastic pieces, minifigure scenes, bright primary studs, toy-world assembly" },
  { id: 53, cat: "科技未來", nameEn: "Low Poly",              nameZh: "低多邊形",     thumb: "thumbs/thumb_53.png",
    prompt: "low poly infographic, faceted geometric 3D shapes, gradient triangles, crisp digital render, cool palette" },
  { id: 54, cat: "科技未來", nameEn: "Glitch Art",            nameZh: "故障藝術",     thumb: "thumbs/thumb_54.png",
    prompt: "glitch art infographic, datamosh distortion, RGB channel split, scanlines, broken-screen digital aesthetic" },
  { id: 55, cat: "藝術設計", nameEn: "Neo-Memphis",           nameZh: "孟菲斯普普",   thumb: "thumbs/thumb_55.png",
    prompt: "Neo-Memphis infographic, playful geometric confetti shapes, squiggles, bold 80s colors, fun pattern blocks" },
  { id: 56, cat: "手繪插畫", nameEn: "Minimal Line Art",      nameZh: "極簡線稿",     thumb: "thumbs/thumb_56.png",
    prompt: "minimalist single-line infographic, continuous contour icons, lots of white space, one accent color, elegant" },
  { id: 57, cat: "復古懷舊", nameEn: "Retro Sci-Fi",          nameZh: "復古太空",     thumb: "thumbs/thumb_57.png",
    prompt: "1950s retro sci-fi infographic, atomic-age rockets, ringed planets, muted teal and orange, vintage poster print" },
  { id: 58, cat: "藝術設計", nameEn: "Mixed Media Collage",   nameZh: "蒙太奇拼貼",   thumb: "thumbs/thumb_58.png",
    prompt: "mixed-media collage infographic, torn paper, washi tape, magazine cutouts, handwriting, layered scrapbook texture" },
  { id: 59, cat: "藝術設計", nameEn: "Stained Glass",         nameZh: "彩繪玻璃",     thumb: "thumbs/thumb_59.png",
    prompt: "stained glass infographic, leaded color segments, glowing jewel panels, bold black outlines, cathedral motif" },
  { id: 60, cat: "手繪插畫", nameEn: "Kawaii Journal",        nameZh: "卡哇伊手帳",   thumb: "thumbs/thumb_60.png",
    prompt: "kawaii infographic, cute pastel mascots, rounded bubbly icons, sticker decorations, soft cheerful palette" },
  { id: 61, cat: "商務簡報", nameEn: "Luxury Gold",           nameZh: "黑金奢華",     thumb: "thumbs/thumb_61.png",
    prompt: "luxury infographic, matte black background, gold foil lines, serif headings, elegant minimal premium layout" },
  { id: 62, cat: "科技未來", nameEn: "Hologram UI",           nameZh: "全像投影",     thumb: "thumbs/thumb_62.png",
    prompt: "holographic HUD infographic, translucent cyan projections, glowing wireframes, floating data panels, sci-fi interface" },
  { id: 63, cat: "手繪插畫", nameEn: "Storybook",             nameZh: "童書插畫",     thumb: "thumbs/thumb_63.png",
    prompt: "children's storybook infographic, soft gouache illustration, friendly characters, warm rounded scenes, cozy palette" },
  { id: 64, cat: "電影影視", nameEn: "Movie Poster",          nameZh: "電影海報",     thumb: "thumbs/thumb_64.png",
    prompt: "blockbuster movie poster infographic, dramatic lighting, layered character montage, bold title treatment, epic mood" }
];
